version: '3.8'

services:
  db:
    image: mysql:8.4
    container_name: mysql_db_swift
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_swift_data:/var/lib/mysql
    networks:
      - swift-network
    ports:
      - "3307:3306"

  app:
    container_name: spring_app_swift
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - swift-network

volumes:
  mysql_swift_data:

networks:
  swift-network:
    driver: bridge